<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Achievement;

class AchievementSeeder extends Seeder
{
    public function run(): void
    {
        $achievements = [
            // Workout Achievements
            [
                'key' => 'first_workout',
                'name_en' => 'First Steps',
                'name_fr' => 'Premiers Pas',
                'name_ar' => 'الخطوات الأولى',
                'description_en' => 'Complete your first workout',
                'description_fr' => 'Terminez votre premier entraînement',
                'description_ar' => 'أكمل تمرينك الأول',
                'icon' => 'figure.walk',
                'points' => 10,
                'category' => 'workout',
            ],
            [
                'key' => 'workout_10',
                'name_en' => 'Dedicated',
                'name_fr' => 'Dévoué',
                'name_ar' => 'مخلص',
                'description_en' => 'Complete 10 workouts',
                'description_fr' => 'Terminez 10 entraînements',
                'description_ar' => 'أكمل 10 تمارين',
                'icon' => 'flame.fill',
                'points' => 25,
                'category' => 'workout',
            ],
            [
                'key' => 'workout_50',
                'name_en' => 'Fitness Warrior',
                'name_fr' => 'Guerrier Fitness',
                'name_ar' => 'محارب اللياقة',
                'description_en' => 'Complete 50 workouts',
                'description_fr' => 'Terminez 50 entraînements',
                'description_ar' => 'أكمل 50 تمرين',
                'icon' => 'bolt.fill',
                'points' => 100,
                'category' => 'workout',
            ],
            [
                'key' => 'workout_100',
                'name_en' => 'Century Club',
                'name_fr' => 'Club des 100',
                'name_ar' => 'نادي المئة',
                'description_en' => 'Complete 100 workouts',
                'description_fr' => 'Terminez 100 entraînements',
                'description_ar' => 'أكمل 100 تمرين',
                'icon' => 'star.fill',
                'points' => 250,
                'category' => 'workout',
            ],

            // Consistency Achievements
            [
                'key' => 'week_streak_4',
                'name_en' => 'Month Strong',
                'name_fr' => 'Un Mois Fort',
                'name_ar' => 'شهر قوي',
                'description_en' => '4 weeks consecutive training',
                'description_fr' => '4 semaines d\'entraînement consécutives',
                'description_ar' => '4 أسابيع تدريب متتالية',
                'icon' => 'calendar.badge.checkmark',
                'points' => 50,
                'category' => 'consistency',
            ],
            [
                'key' => 'week_streak_8',
                'name_en' => 'Two Months Power',
                'name_fr' => 'Deux Mois de Puissance',
                'name_ar' => 'قوة شهرين',
                'description_en' => '8 weeks consecutive training',
                'description_fr' => '8 semaines d\'entraînement consécutives',
                'description_ar' => '8 أسابيع تدريب متتالية',
                'icon' => 'flame.circle.fill',
                'points' => 100,
                'category' => 'consistency',
            ],
            [
                'key' => 'week_streak_12',
                'name_en' => 'Quarter Master',
                'name_fr' => 'Maître du Trimestre',
                'name_ar' => 'سيد الربع',
                'description_en' => '12 weeks consecutive training',
                'description_fr' => '12 semaines d\'entraînement consécutives',
                'description_ar' => '12 أسبوع تدريب متتالي',
                'icon' => 'crown.fill',
                'points' => 200,
                'category' => 'consistency',
            ],
            [
                'key' => 'early_bird',
                'name_en' => 'Early Bird',
                'name_fr' => 'Lève-tôt',
                'name_ar' => 'الباكر',
                'description_en' => 'Complete 10 workouts before 8 AM',
                'description_fr' => 'Terminez 10 entraînements avant 8h',
                'description_ar' => 'أكمل 10 تمارين قبل الساعة 8 صباحاً',
                'icon' => 'sunrise.fill',
                'points' => 30,
                'category' => 'consistency',
            ],

            // Progress Milestones
            [
                'key' => 'progress_25',
                'name_en' => 'Quarter Way',
                'name_fr' => 'Un Quart du Chemin',
                'name_ar' => 'ربع الطريق',
                'description_en' => 'Reach 25% of your goal',
                'description_fr' => 'Atteignez 25% de votre objectif',
                'description_ar' => 'حقق 25٪ من هدفك',
                'icon' => 'chart.bar.fill',
                'points' => 25,
                'category' => 'milestone',
            ],
            [
                'key' => 'progress_50',
                'name_en' => 'Halfway There',
                'name_fr' => 'À Mi-chemin',
                'name_ar' => 'في منتصف الطريق',
                'description_en' => 'Reach 50% of your goal',
                'description_fr' => 'Atteignez 50% de votre objectif',
                'description_ar' => 'حقق 50٪ من هدفك',
                'icon' => 'chart.line.uptrend.xyaxis',
                'points' => 50,
                'category' => 'milestone',
            ],
            [
                'key' => 'progress_75',
                'name_en' => 'Almost There',
                'name_fr' => 'Presque Arrivé',
                'name_ar' => 'تقريباً هناك',
                'description_en' => 'Reach 75% of your goal',
                'description_fr' => 'Atteignez 75% de votre objectif',
                'description_ar' => 'حقق 75٪ من هدفك',
                'icon' => 'target',
                'points' => 75,
                'category' => 'milestone',
            ],
            [
                'key' => 'goal_complete',
                'name_en' => 'Goal Crusher',
                'name_fr' => 'Objectif Atteint',
                'name_ar' => 'محقق الأهداف',
                'description_en' => 'Complete your fitness goal',
                'description_fr' => 'Complétez votre objectif fitness',
                'description_ar' => 'أكمل هدف اللياقة الخاص بك',
                'icon' => 'trophy.fill',
                'points' => 150,
                'category' => 'milestone',
            ],

            // Nutrition Achievements
            [
                'key' => 'nutrition_tracker',
                'name_en' => 'Nutrition Tracker',
                'name_fr' => 'Suivi Nutritionnel',
                'name_ar' => 'متتبع التغذية',
                'description_en' => 'Log meals for 7 consecutive days',
                'description_fr' => 'Enregistrez vos repas pendant 7 jours consécutifs',
                'description_ar' => 'سجل وجباتك لمدة 7 أيام متتالية',
                'icon' => 'fork.knife',
                'points' => 30,
                'category' => 'nutrition',
            ],
            [
                'key' => 'hydration_hero',
                'name_en' => 'Hydration Hero',
                'name_fr' => 'Héros de l\'Hydratation',
                'name_ar' => 'بطل الترطيب',
                'description_en' => 'Track water intake for 14 days',
                'description_fr' => 'Suivez votre consommation d\'eau pendant 14 jours',
                'description_ar' => 'تتبع شرب الماء لمدة 14 يوماً',
                'icon' => 'drop.fill',
                'points' => 40,
                'category' => 'nutrition',
            ],

            // Special Achievements
            [
                'key' => 'profile_complete',
                'name_en' => 'Profile Pro',
                'name_fr' => 'Profil Complet',
                'name_ar' => 'محترف الملف الشخصي',
                'description_en' => 'Complete your full profile',
                'description_fr' => 'Complétez votre profil complet',
                'description_ar' => 'أكمل ملفك الشخصي الكامل',
                'icon' => 'person.crop.circle.badge.checkmark',
                'points' => 15,
                'category' => 'special',
            ],
            [
                'key' => 'first_weight_log',
                'name_en' => 'Weigh In',
                'name_fr' => 'Première Pesée',
                'name_ar' => 'أول وزن',
                'description_en' => 'Log your first weight measurement',
                'description_fr' => 'Enregistrez votre première mesure de poids',
                'description_ar' => 'سجل أول قياس للوزن',
                'icon' => 'scalemass.fill',
                'points' => 10,
                'category' => 'special',
            ],
            [
                'key' => 'kine_master',
                'name_en' => 'Kine Master',
                'name_fr' => 'Maître Kiné',
                'name_ar' => 'خبير العلاج الطبيعي',
                'description_en' => 'Complete 20 kine exercises',
                'description_fr' => 'Terminez 20 exercices de kiné',
                'description_ar' => 'أكمل 20 تمرين علاج طبيعي',
                'icon' => 'figure.flexibility',
                'points' => 50,
                'category' => 'special',
            ],
            [
                'key' => 'social_butterfly',
                'name_en' => 'Social Butterfly',
                'name_fr' => 'Papillon Social',
                'name_ar' => 'الفراشة الاجتماعية',
                'description_en' => 'Share your progress 5 times',
                'description_fr' => 'Partagez vos progrès 5 fois',
                'description_ar' => 'شارك تقدمك 5 مرات',
                'icon' => 'person.3.fill',
                'points' => 20,
                'category' => 'special',
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::create($achievement);
        }
    }
}
