<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PropheticRemedy;

class PropheticMedicineSeeder extends Seeder
{
    public function run(): void
    {
        $remedies = [
            // ─────────────────────────────────────────────
            // 1. TOUX & PHARYNGITE
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'toux',
                'condition_name_fr' => 'Toux & Pharyngite',
                'condition_name_en' => 'Cough & Pharyngitis',
                'condition_name_ar' => 'السعال والتهاب الحلق',
                'element_name_fr'   => 'Nigelle',
                'element_name_en'   => 'Black Seed',
                'element_name_ar'   => 'حبة البركة',
                'mechanism_fr'      => 'Bronchodilatateur et anti-inflammatoire',
                'mechanism_en'      => 'Bronchodilator and anti-inflammatory',
                'mechanism_ar'      => 'موسع للشعب الهوائية ومضاد للالتهابات',
                'recipe_fr'         => '1 cuillère à café d\'huile de nigelle avec du miel, 2 fois par jour',
                'recipe_en'         => '1 tsp black seed oil with honey, 2x/day',
                'recipe_ar'         => 'ملعقة صغيرة من زيت حبة البركة مع العسل، مرتين يوميًا',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'toux',
                'condition_name_fr' => 'Toux & Pharyngite',
                'condition_name_en' => 'Cough & Pharyngitis',
                'condition_name_ar' => 'السعال والتهاب الحلق',
                'element_name_fr'   => 'Costus Indien',
                'element_name_en'   => 'Indian Costus',
                'element_name_ar'   => 'القسط الهندي',
                'mechanism_fr'      => 'Antiseptique pour les bronches et les sinus',
                'mechanism_en'      => 'Antiseptic for bronchi and sinuses',
                'mechanism_ar'      => 'مطهر للشعب الهوائية والجيوب الأنفية',
                'recipe_fr'         => 'Inhaler la vapeur avec de la poudre de costus',
                'recipe_en'         => 'Inhale steam with costus powder',
                'recipe_ar'         => 'استنشاق البخار مع مسحوق القسط',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'toux',
                'condition_name_fr' => 'Toux & Pharyngite',
                'condition_name_en' => 'Cough & Pharyngitis',
                'condition_name_ar' => 'السعال والتهاب الحلق',
                'element_name_fr'   => 'Miel de Thym',
                'element_name_en'   => 'Thyme Honey',
                'element_name_ar'   => 'عسل الزعتر',
                'mechanism_fr'      => 'Antibactérien, apaise la gorge',
                'mechanism_en'      => 'Antibacterial, soothes throat',
                'mechanism_ar'      => 'مضاد للبكتيريا، يهدئ الحلق',
                'recipe_fr'         => '1 cuillère à soupe dans de l\'eau tiède, 3 fois par jour',
                'recipe_en'         => '1 tbsp in warm water, 3x/day',
                'recipe_ar'         => 'ملعقة كبيرة في ماء دافئ، 3 مرات يوميًا',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'toux',
                'condition_name_fr' => 'Toux & Pharyngite',
                'condition_name_en' => 'Cough & Pharyngitis',
                'condition_name_ar' => 'السعال والتهاب الحلق',
                'element_name_fr'   => 'Ail',
                'element_name_en'   => 'Garlic',
                'element_name_ar'   => 'الثوم',
                'mechanism_fr'      => 'Fluidifiant riche en soufre',
                'mechanism_en'      => 'Sulfur-rich fluidifier',
                'mechanism_ar'      => 'مذيب غني بالكبريت',
                'recipe_fr'         => 'Écraser 2 gousses, mélanger avec du miel, avaler',
                'recipe_en'         => 'Crush 2 cloves, mix with honey, swallow',
                'recipe_ar'         => 'اهرس فصين، اخلطهما مع العسل، وابلع',
                'sort_order'        => 4,
            ],
            [
                'condition_key'     => 'toux',
                'condition_name_fr' => 'Toux & Pharyngite',
                'condition_name_en' => 'Cough & Pharyngitis',
                'condition_name_ar' => 'السعال والتهاب الحلق',
                'element_name_fr'   => 'Oignon',
                'element_name_en'   => 'Onion',
                'element_name_ar'   => 'البصل',
                'mechanism_fr'      => 'Expectorant naturel',
                'mechanism_en'      => 'Natural expectorant',
                'mechanism_ar'      => 'طارد طبيعي للبلغم',
                'recipe_fr'         => 'Sirop d\'oignon : trancher un oignon, couvrir de miel, laisser reposer 6h',
                'recipe_en'         => 'Onion syrup - slice onion, cover with honey, let sit 6h',
                'recipe_ar'         => 'شراب البصل: قطّع بصلة، غطّها بالعسل، اتركها 6 ساعات',
                'sort_order'        => 5,
            ],

            // ─────────────────────────────────────────────
            // 2. MIGRAINE
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'migraine',
                'condition_name_fr' => 'Migraine',
                'condition_name_en' => 'Migraine',
                'condition_name_ar' => 'الصداع النصفي',
                'element_name_fr'   => 'Hijama',
                'element_name_en'   => 'Cupping',
                'element_name_ar'   => 'الحجامة',
                'mechanism_fr'      => 'Élimine la stase sanguine',
                'mechanism_en'      => 'Eliminates blood stasis',
                'mechanism_ar'      => 'يزيل ركود الدم',
                'recipe_fr'         => 'Appliquer sur le sommet de la tête et l\'arrière du cou',
                'recipe_en'         => 'Apply on head apex and back of neck',
                'recipe_ar'         => 'يُطبّق على قمة الرأس وخلف الرقبة',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'migraine',
                'condition_name_fr' => 'Migraine',
                'condition_name_en' => 'Migraine',
                'condition_name_ar' => 'الصداع النصفي',
                'element_name_fr'   => 'Huile de Nigelle',
                'element_name_en'   => 'Black Seed Oil',
                'element_name_ar'   => 'زيت حبة البركة',
                'mechanism_fr'      => 'Inhibition des prostaglandines',
                'mechanism_en'      => 'Prostaglandin inhibition',
                'mechanism_ar'      => 'تثبيط البروستاجلاندين',
                'recipe_fr'         => 'Masser les tempes avec l\'huile, prendre 1 cuillère à café par voie orale',
                'recipe_en'         => 'Massage temples with oil, take 1 tsp orally',
                'recipe_ar'         => 'تدليك الصدغين بالزيت، وتناول ملعقة صغيرة عن طريق الفم',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'migraine',
                'condition_name_fr' => 'Migraine',
                'condition_name_en' => 'Migraine',
                'condition_name_ar' => 'الصداع النصفي',
                'element_name_fr'   => 'Menthe Poivrée',
                'element_name_en'   => 'Peppermint',
                'element_name_ar'   => 'النعناع الفلفلي',
                'mechanism_fr'      => 'Analgésie vasoconstrictive',
                'mechanism_en'      => 'Vasoconstrictive analgesia',
                'mechanism_ar'      => 'تسكين بتضييق الأوعية الدموية',
                'recipe_fr'         => 'Appliquer l\'huile essentielle sur les tempes, boire une tisane de menthe poivrée',
                'recipe_en'         => 'Apply essential oil on temples, drink peppermint tea',
                'recipe_ar'         => 'ضع الزيت العطري على الصدغين، واشرب شاي النعناع الفلفلي',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'migraine',
                'condition_name_fr' => 'Migraine',
                'condition_name_en' => 'Migraine',
                'condition_name_ar' => 'الصداع النصفي',
                'element_name_fr'   => 'Miel de Lavande',
                'element_name_en'   => 'Lavender Honey',
                'element_name_ar'   => 'عسل اللافندر',
                'mechanism_fr'      => 'Soulagement de la tension nerveuse',
                'mechanism_en'      => 'Nervous tension relief',
                'mechanism_ar'      => 'تخفيف التوتر العصبي',
                'recipe_fr'         => '1 cuillère à soupe dans du lait tiède avant le coucher',
                'recipe_en'         => '1 tbsp in warm milk before bed',
                'recipe_ar'         => 'ملعقة كبيرة في حليب دافئ قبل النوم',
                'sort_order'        => 4,
            ],
            [
                'condition_key'     => 'migraine',
                'condition_name_fr' => 'Migraine',
                'condition_name_en' => 'Migraine',
                'condition_name_ar' => 'الصداع النصفي',
                'element_name_fr'   => 'Magnésium',
                'element_name_en'   => 'Magnesium',
                'element_name_ar'   => 'المغنيسيوم',
                'mechanism_fr'      => '300-400 mg/jour de bisglycinate',
                'mechanism_en'      => '300-400 mg/day bisglycinate',
                'mechanism_ar'      => '300-400 ملغ/يوم بيسجليسينات',
                'recipe_fr'         => 'Prendre le complément quotidiennement avec le dîner',
                'recipe_en'         => 'Take supplement daily with dinner',
                'recipe_ar'         => 'تناول المكمل يوميًا مع العشاء',
                'sort_order'        => 5,
            ],

            // ─────────────────────────────────────────────
            // 3. DÉPRESSION
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'depression',
                'condition_name_fr' => 'Dépression',
                'condition_name_en' => 'Depression',
                'condition_name_ar' => 'الاكتئاب',
                'element_name_fr'   => 'Talbina',
                'element_name_en'   => 'Talbina',
                'element_name_ar'   => 'التلبينة',
                'mechanism_fr'      => 'Tryptophane pour la production de sérotonine',
                'mechanism_en'      => 'Tryptophan for serotonin production',
                'mechanism_ar'      => 'التربتوفان لإنتاج السيروتونين',
                'recipe_fr'         => 'Cuire la farine d\'orge dans du lait, ajouter du miel, manger tiède',
                'recipe_en'         => 'Cook barley flour in milk, add honey, eat warm',
                'recipe_ar'         => 'اطبخ دقيق الشعير في الحليب، أضف العسل، وتناوله دافئًا',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'depression',
                'condition_name_fr' => 'Dépression',
                'condition_name_en' => 'Depression',
                'condition_name_ar' => 'الاكتئاب',
                'element_name_fr'   => 'Dattes Ajwa',
                'element_name_en'   => 'Ajwa Dates',
                'element_name_ar'   => 'تمر العجوة',
                'mechanism_fr'      => 'Magnésium et sucres naturels',
                'mechanism_en'      => 'Magnesium + natural sugars',
                'mechanism_ar'      => 'المغنيسيوم والسكريات الطبيعية',
                'recipe_fr'         => 'Manger 7 dattes chaque matin',
                'recipe_en'         => 'Eat 7 dates each morning',
                'recipe_ar'         => 'تناول 7 تمرات كل صباح',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'depression',
                'condition_name_fr' => 'Dépression',
                'condition_name_en' => 'Depression',
                'condition_name_ar' => 'الاكتئاب',
                'element_name_fr'   => 'Safran',
                'element_name_en'   => 'Saffron',
                'element_name_ar'   => 'الزعفران',
                'mechanism_fr'      => 'Composé naturel équivalent aux ISRS',
                'mechanism_en'      => 'SSRI equivalent natural compound',
                'mechanism_ar'      => 'مركب طبيعي مكافئ لمثبطات استرداد السيروتونين',
                'recipe_fr'         => 'Infuser 2-3 filaments dans de l\'eau tiède, boire quotidiennement',
                'recipe_en'         => 'Infuse 2-3 threads in warm water, drink daily',
                'recipe_ar'         => 'انقع 2-3 خيوط في ماء دافئ، واشربه يوميًا',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'depression',
                'condition_name_fr' => 'Dépression',
                'condition_name_en' => 'Depression',
                'condition_name_ar' => 'الاكتئاب',
                'element_name_fr'   => 'Millepertuis',
                'element_name_en'   => 'St. John\'s Wort',
                'element_name_ar'   => 'عشبة القديس يوحنا',
                'mechanism_fr'      => 'Régulation de la dopamine et de la noradrénaline',
                'mechanism_en'      => 'Dopamine/noradrenaline regulation',
                'mechanism_ar'      => 'تنظيم الدوبامين والنورأدرينالين',
                'recipe_fr'         => 'Tisane ou gélule, 300 mg 3 fois par jour',
                'recipe_en'         => 'Tea or capsule, 300mg 3x/day',
                'recipe_ar'         => 'شاي أو كبسولة، 300 ملغ 3 مرات يوميًا',
                'sort_order'        => 4,
            ],
            [
                'condition_key'     => 'depression',
                'condition_name_fr' => 'Dépression',
                'condition_name_en' => 'Depression',
                'condition_name_ar' => 'الاكتئاب',
                'element_name_fr'   => 'Noix',
                'element_name_en'   => 'Walnuts',
                'element_name_ar'   => 'الجوز',
                'mechanism_fr'      => 'Source d\'oméga-3',
                'mechanism_en'      => 'Omega-3 source',
                'mechanism_ar'      => 'مصدر أوميغا 3',
                'recipe_fr'         => 'Manger une poignée quotidiennement (30g)',
                'recipe_en'         => 'Eat handful daily (30g)',
                'recipe_ar'         => 'تناول حفنة يوميًا (30 غ)',
                'sort_order'        => 5,
            ],

            // ─────────────────────────────────────────────
            // 4. INSOMNIE
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'insomnia',
                'condition_name_fr' => 'Insomnie',
                'condition_name_en' => 'Insomnia',
                'condition_name_ar' => 'الأرق',
                'element_name_fr'   => 'Miel & Lait tiède',
                'element_name_en'   => 'Honey & Warm Milk',
                'element_name_ar'   => 'العسل والحليب الدافئ',
                'mechanism_fr'      => 'Apport de tryptophane',
                'mechanism_en'      => 'Tryptophan delivery',
                'mechanism_ar'      => 'توصيل التربتوفان',
                'recipe_fr'         => '1 cuillère à soupe de miel dans du lait tiède avant le coucher',
                'recipe_en'         => '1 tbsp honey in warm milk before bed',
                'recipe_ar'         => 'ملعقة كبيرة من العسل في حليب دافئ قبل النوم',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'insomnia',
                'condition_name_fr' => 'Insomnie',
                'condition_name_en' => 'Insomnia',
                'condition_name_ar' => 'الأرق',
                'element_name_fr'   => 'Valériane',
                'element_name_en'   => 'Valerian',
                'element_name_ar'   => 'حشيشة الهر',
                'mechanism_fr'      => 'Sédatif naturel (GABA)',
                'mechanism_en'      => 'Natural sedative (GABA)',
                'mechanism_ar'      => 'مهدئ طبيعي (غابا)',
                'recipe_fr'         => 'Gélule de 300-600 mg, 1h avant le coucher',
                'recipe_en'         => '300-600mg capsule 1h before bed',
                'recipe_ar'         => 'كبسولة 300-600 ملغ، ساعة قبل النوم',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'insomnia',
                'condition_name_fr' => 'Insomnie',
                'condition_name_en' => 'Insomnia',
                'condition_name_ar' => 'الأرق',
                'element_name_fr'   => 'Passiflore',
                'element_name_en'   => 'Passionflower',
                'element_name_ar'   => 'زهرة الآلام',
                'mechanism_fr'      => 'Calmant anxiolytique',
                'mechanism_en'      => 'Anxiolytic calming',
                'mechanism_ar'      => 'مهدئ مضاد للقلق',
                'recipe_fr'         => 'Infusion de tisane 30 minutes avant le coucher',
                'recipe_en'         => 'Tea infusion 30 min before bed',
                'recipe_ar'         => 'منقوع شاي قبل النوم بـ30 دقيقة',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'insomnia',
                'condition_name_fr' => 'Insomnie',
                'condition_name_en' => 'Insomnia',
                'condition_name_ar' => 'الأرق',
                'element_name_fr'   => 'Cerise Montmorency',
                'element_name_en'   => 'Montmorency Cherry',
                'element_name_ar'   => 'كرز مونتمورنسي',
                'mechanism_fr'      => 'Source directe de mélatonine',
                'mechanism_en'      => 'Direct melatonin source',
                'mechanism_ar'      => 'مصدر مباشر للميلاتونين',
                'recipe_fr'         => '30 ml de jus avant le coucher',
                'recipe_en'         => '30ml juice before bed',
                'recipe_ar'         => '30 مل من العصير قبل النوم',
                'sort_order'        => 4,
            ],
            [
                'condition_key'     => 'insomnia',
                'condition_name_fr' => 'Insomnie',
                'condition_name_en' => 'Insomnia',
                'condition_name_ar' => 'الأرق',
                'element_name_fr'   => 'Ashwagandha',
                'element_name_en'   => 'Ashwagandha',
                'element_name_ar'   => 'أشواغاندا',
                'mechanism_fr'      => 'Réduction du cortisol',
                'mechanism_en'      => 'Cortisol reduction',
                'mechanism_ar'      => 'تقليل الكورتيزول',
                'recipe_fr'         => 'Gélule de 300 mg avec le dîner',
                'recipe_en'         => '300mg capsule with dinner',
                'recipe_ar'         => 'كبسولة 300 ملغ مع العشاء',
                'sort_order'        => 5,
            ],

            // ─────────────────────────────────────────────
            // 5. STRESS & ANXIÉTÉ
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'stress',
                'condition_name_fr' => 'Stress & Anxiété',
                'condition_name_en' => 'Stress & Anxiety',
                'condition_name_ar' => 'التوتر والقلق',
                'element_name_fr'   => 'Huile de Nigelle',
                'element_name_en'   => 'Black Seed Oil',
                'element_name_ar'   => 'زيت حبة البركة',
                'mechanism_fr'      => 'Propriétés adaptogènes',
                'mechanism_en'      => 'Adaptogenic properties',
                'mechanism_ar'      => 'خصائص تكيفية',
                'recipe_fr'         => '1 cuillère à café matin et soir',
                'recipe_en'         => '1 tsp morning and evening',
                'recipe_ar'         => 'ملعقة صغيرة صباحًا ومساءً',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'stress',
                'condition_name_fr' => 'Stress & Anxiété',
                'condition_name_en' => 'Stress & Anxiety',
                'condition_name_ar' => 'التوتر والقلق',
                'element_name_fr'   => 'Rhodiola',
                'element_name_en'   => 'Rhodiola',
                'element_name_ar'   => 'الروديولا',
                'mechanism_fr'      => 'Régulation des hormones de stress',
                'mechanism_en'      => 'Stress hormone regulation',
                'mechanism_ar'      => 'تنظيم هرمونات التوتر',
                'recipe_fr'         => 'Gélule de 200-400 mg le matin',
                'recipe_en'         => '200-400mg capsule in morning',
                'recipe_ar'         => 'كبسولة 200-400 ملغ في الصباح',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'stress',
                'condition_name_fr' => 'Stress & Anxiété',
                'condition_name_en' => 'Stress & Anxiety',
                'condition_name_ar' => 'التوتر والقلق',
                'element_name_fr'   => 'Miel d\'Oranger',
                'element_name_en'   => 'Orange Blossom Honey',
                'element_name_ar'   => 'عسل زهر البرتقال',
                'mechanism_fr'      => 'Apaisement du système nerveux central',
                'mechanism_en'      => 'CNS calming',
                'mechanism_ar'      => 'تهدئة الجهاز العصبي المركزي',
                'recipe_fr'         => '1 cuillère à soupe dans une tisane de camomille',
                'recipe_en'         => '1 tbsp in chamomile tea',
                'recipe_ar'         => 'ملعقة كبيرة في شاي البابونج',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'stress',
                'condition_name_fr' => 'Stress & Anxiété',
                'condition_name_en' => 'Stress & Anxiety',
                'condition_name_ar' => 'التوتر والقلق',
                'element_name_fr'   => 'Verveine',
                'element_name_en'   => 'Verbena',
                'element_name_ar'   => 'لويزة',
                'mechanism_fr'      => 'Calmant des spasmes',
                'mechanism_en'      => 'Spasm calming',
                'mechanism_ar'      => 'مهدئ للتشنجات',
                'recipe_fr'         => 'Infusion 2-3 tasses par jour',
                'recipe_en'         => 'Infusion 2-3 cups/day',
                'recipe_ar'         => 'منقوع 2-3 أكواب يوميًا',
                'sort_order'        => 4,
            ],
            [
                'condition_key'     => 'stress',
                'condition_name_fr' => 'Stress & Anxiété',
                'condition_name_en' => 'Stress & Anxiety',
                'condition_name_ar' => 'التوتر والقلق',
                'element_name_fr'   => 'Magnésium Bisglycinate',
                'element_name_en'   => 'Magnesium Bisglycinate',
                'element_name_ar'   => 'بيسجليسينات المغنيسيوم',
                'mechanism_fr'      => '300 mg par jour',
                'mechanism_en'      => '300mg/day',
                'mechanism_ar'      => '300 ملغ يوميًا',
                'recipe_fr'         => 'Prendre avec le dîner',
                'recipe_en'         => 'Take with dinner',
                'recipe_ar'         => 'تناوله مع العشاء',
                'sort_order'        => 5,
            ],

            // ─────────────────────────────────────────────
            // 6. SINUSITE
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'sinusite',
                'condition_name_fr' => 'Sinusite',
                'condition_name_en' => 'Sinusitis',
                'condition_name_ar' => 'التهاب الجيوب الأنفية',
                'element_name_fr'   => 'Costus Indien',
                'element_name_en'   => 'Indian Costus',
                'element_name_ar'   => 'القسط الهندي',
                'mechanism_fr'      => 'Instillation nasale',
                'mechanism_en'      => 'Nasal instillation',
                'mechanism_ar'      => 'تقطير أنفي',
                'recipe_fr'         => 'Mélanger la poudre de costus avec de l\'huile d\'olive, instiller 2 gouttes par narine',
                'recipe_en'         => 'Mix costus powder with olive oil, instill 2 drops per nostril',
                'recipe_ar'         => 'اخلط مسحوق القسط مع زيت الزيتون، ضع نقطتين في كل فتحة أنف',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'sinusite',
                'condition_name_fr' => 'Sinusite',
                'condition_name_en' => 'Sinusitis',
                'condition_name_ar' => 'التهاب الجيوب الأنفية',
                'element_name_fr'   => 'Nigelle',
                'element_name_en'   => 'Black Seed',
                'element_name_ar'   => 'حبة البركة',
                'mechanism_fr'      => 'Inhalation de vapeur',
                'mechanism_en'      => 'Steam inhalation',
                'mechanism_ar'      => 'استنشاق البخار',
                'recipe_fr'         => 'Ajouter l\'huile à de l\'eau bouillante, inhaler la vapeur 10 minutes',
                'recipe_en'         => 'Add oil to boiling water, inhale steam 10 min',
                'recipe_ar'         => 'أضف الزيت إلى ماء مغلي، واستنشق البخار لمدة 10 دقائق',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'sinusite',
                'condition_name_fr' => 'Sinusite',
                'condition_name_en' => 'Sinusitis',
                'condition_name_ar' => 'التهاب الجيوب الأنفية',
                'element_name_fr'   => 'Miel de Thym',
                'element_name_en'   => 'Thyme Honey',
                'element_name_ar'   => 'عسل الزعتر',
                'mechanism_fr'      => 'Activité antibiotique',
                'mechanism_en'      => 'Antibiotic activity',
                'mechanism_ar'      => 'نشاط مضاد حيوي',
                'recipe_fr'         => 'Rinçage nasal avec de l\'eau au miel diluée',
                'recipe_en'         => 'Nasal rinse with diluted honey water',
                'recipe_ar'         => 'غسل أنفي بماء العسل المخفف',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'sinusite',
                'condition_name_fr' => 'Sinusite',
                'condition_name_en' => 'Sinusitis',
                'condition_name_ar' => 'التهاب الجيوب الأنفية',
                'element_name_fr'   => 'Ail',
                'element_name_en'   => 'Garlic',
                'element_name_ar'   => 'الثوم',
                'mechanism_fr'      => 'Mobilisateur de soufre',
                'mechanism_en'      => 'Sulfur mobilizer',
                'mechanism_ar'      => 'محرك الكبريت',
                'recipe_fr'         => 'Inhaler la vapeur d\'ail écrasé',
                'recipe_en'         => 'Inhale crushed garlic steam',
                'recipe_ar'         => 'استنشاق بخار الثوم المهروس',
                'sort_order'        => 4,
            ],

            // ─────────────────────────────────────────────
            // 7. DIABÈTE
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'diabetes',
                'condition_name_fr' => 'Diabète',
                'condition_name_en' => 'Diabetes',
                'condition_name_ar' => 'مرض السكري',
                'element_name_fr'   => 'Nigelle',
                'element_name_en'   => 'Black Seed',
                'element_name_ar'   => 'حبة البركة',
                'mechanism_fr'      => 'Sensibilisateur à l\'insuline',
                'mechanism_en'      => 'Insulin sensitizer',
                'mechanism_ar'      => 'محسّن لحساسية الأنسولين',
                'recipe_fr'         => '1 cuillère à café de graines moulues avant les repas',
                'recipe_en'         => '1 tsp ground seeds before meals',
                'recipe_ar'         => 'ملعقة صغيرة من البذور المطحونة قبل الوجبات',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'diabetes',
                'condition_name_fr' => 'Diabète',
                'condition_name_en' => 'Diabetes',
                'condition_name_ar' => 'مرض السكري',
                'element_name_fr'   => 'Cannelle',
                'element_name_en'   => 'Cinnamon',
                'element_name_ar'   => 'القرفة',
                'mechanism_fr'      => 'Régulation de la glycémie',
                'mechanism_en'      => 'Blood sugar regulation',
                'mechanism_ar'      => 'تنظيم سكر الدم',
                'recipe_fr'         => '1/2 cuillère à café de cannelle dans les aliments quotidiennement',
                'recipe_en'         => '1/2 tsp cinnamon in food daily',
                'recipe_ar'         => 'نصف ملعقة صغيرة من القرفة في الطعام يوميًا',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'diabetes',
                'condition_name_fr' => 'Diabète',
                'condition_name_en' => 'Diabetes',
                'condition_name_ar' => 'مرض السكري',
                'element_name_fr'   => 'Fenugrec',
                'element_name_en'   => 'Fenugreek',
                'element_name_ar'   => 'الحلبة',
                'mechanism_fr'      => 'Abaisse la glycémie',
                'mechanism_en'      => 'Lowers blood glucose',
                'mechanism_ar'      => 'يخفض مستوى السكر في الدم',
                'recipe_fr'         => 'Tremper les graines toute la nuit, boire l\'eau le matin',
                'recipe_en'         => 'Soak seeds overnight, drink water in morning',
                'recipe_ar'         => 'انقع البذور طوال الليل، واشرب الماء في الصباح',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'diabetes',
                'condition_name_fr' => 'Diabète',
                'condition_name_en' => 'Diabetes',
                'condition_name_ar' => 'مرض السكري',
                'element_name_fr'   => 'Vinaigre de Cidre',
                'element_name_en'   => 'Apple Cider Vinegar',
                'element_name_ar'   => 'خل التفاح',
                'mechanism_fr'      => 'Ralentit l\'absorption du glucose',
                'mechanism_en'      => 'Slows glucose absorption',
                'mechanism_ar'      => 'يبطئ امتصاص الجلوكوز',
                'recipe_fr'         => '1 cuillère à soupe dans de l\'eau avant les repas',
                'recipe_en'         => '1 tbsp in water before meals',
                'recipe_ar'         => 'ملعقة كبيرة في الماء قبل الوجبات',
                'sort_order'        => 4,
            ],

            // ─────────────────────────────────────────────
            // 8. HYPERTENSION
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'hypertension',
                'condition_name_fr' => 'Hypertension',
                'condition_name_en' => 'Hypertension',
                'condition_name_ar' => 'ارتفاع ضغط الدم',
                'element_name_fr'   => 'Ail',
                'element_name_en'   => 'Garlic',
                'element_name_ar'   => 'الثوم',
                'mechanism_fr'      => 'Vasodilatateur',
                'mechanism_en'      => 'Vasodilator',
                'mechanism_ar'      => 'موسع للأوعية الدموية',
                'recipe_fr'         => '2 gousses par jour à jeun',
                'recipe_en'         => '2 cloves daily on empty stomach',
                'recipe_ar'         => 'فصان يوميًا على معدة فارغة',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'hypertension',
                'condition_name_fr' => 'Hypertension',
                'condition_name_en' => 'Hypertension',
                'condition_name_ar' => 'ارتفاع ضغط الدم',
                'element_name_fr'   => 'Hibiscus',
                'element_name_en'   => 'Hibiscus',
                'element_name_ar'   => 'الكركديه',
                'mechanism_fr'      => 'Inhibiteur naturel de l\'ECA',
                'mechanism_en'      => 'Natural ACE inhibitor',
                'mechanism_ar'      => 'مثبط طبيعي للإنزيم المحول للأنجيوتنسين',
                'recipe_fr'         => 'Infusion à froid, 2-3 tasses par jour',
                'recipe_en'         => 'Cold infusion, 2-3 cups/day',
                'recipe_ar'         => 'منقوع بارد، 2-3 أكواب يوميًا',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'hypertension',
                'condition_name_fr' => 'Hypertension',
                'condition_name_en' => 'Hypertension',
                'condition_name_ar' => 'ارتفاع ضغط الدم',
                'element_name_fr'   => 'Nigelle',
                'element_name_en'   => 'Black Seed',
                'element_name_ar'   => 'حبة البركة',
                'mechanism_fr'      => 'Réduction de la pression artérielle',
                'mechanism_en'      => 'Blood pressure reduction',
                'mechanism_ar'      => 'خفض ضغط الدم',
                'recipe_fr'         => '1 cuillère à café d\'huile par jour',
                'recipe_en'         => '1 tsp oil daily',
                'recipe_ar'         => 'ملعقة صغيرة من الزيت يوميًا',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'hypertension',
                'condition_name_fr' => 'Hypertension',
                'condition_name_en' => 'Hypertension',
                'condition_name_ar' => 'ارتفاع ضغط الدم',
                'element_name_fr'   => 'Olive',
                'element_name_en'   => 'Olive',
                'element_name_ar'   => 'الزيتون',
                'mechanism_fr'      => 'Riche en polyphénols',
                'mechanism_en'      => 'Rich in polyphenols',
                'mechanism_ar'      => 'غني بالبوليفينولات',
                'recipe_fr'         => '2 cuillères à soupe d\'huile d\'olive extra vierge par jour',
                'recipe_en'         => '2 tbsp extra virgin olive oil daily',
                'recipe_ar'         => 'ملعقتان كبيرتان من زيت الزيتون البكر يوميًا',
                'sort_order'        => 4,
            ],

            // ─────────────────────────────────────────────
            // 9. OBÉSITÉ
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'obesity',
                'condition_name_fr' => 'Obésité',
                'condition_name_en' => 'Obesity',
                'condition_name_ar' => 'السمنة',
                'element_name_fr'   => 'Nigelle',
                'element_name_en'   => 'Black Seed',
                'element_name_ar'   => 'حبة البركة',
                'mechanism_fr'      => 'Activateur métabolique',
                'mechanism_en'      => 'Metabolic activator',
                'mechanism_ar'      => 'منشط للأيض',
                'recipe_fr'         => '1 cuillère à café d\'huile avec du jus de citron, le matin',
                'recipe_en'         => '1 tsp oil with lemon juice, morning',
                'recipe_ar'         => 'ملعقة صغيرة من الزيت مع عصير الليمون، صباحًا',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'obesity',
                'condition_name_fr' => 'Obésité',
                'condition_name_en' => 'Obesity',
                'condition_name_ar' => 'السمنة',
                'element_name_fr'   => 'Vinaigre de Cidre',
                'element_name_en'   => 'Apple Cider Vinegar',
                'element_name_ar'   => 'خل التفاح',
                'mechanism_fr'      => 'Coupe-faim',
                'mechanism_en'      => 'Appetite suppressant',
                'mechanism_ar'      => 'مثبط للشهية',
                'recipe_fr'         => '1 cuillère à soupe dans de l\'eau avant les repas',
                'recipe_en'         => '1 tbsp in water before meals',
                'recipe_ar'         => 'ملعقة كبيرة في الماء قبل الوجبات',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'obesity',
                'condition_name_fr' => 'Obésité',
                'condition_name_en' => 'Obesity',
                'condition_name_ar' => 'السمنة',
                'element_name_fr'   => 'Thé Vert',
                'element_name_en'   => 'Green Tea',
                'element_name_ar'   => 'الشاي الأخضر',
                'mechanism_fr'      => 'Stimulateur de thermogenèse',
                'mechanism_en'      => 'Thermogenesis booster',
                'mechanism_ar'      => 'محفز لتوليد الحرارة',
                'recipe_fr'         => '3-4 tasses par jour entre les repas',
                'recipe_en'         => '3-4 cups/day between meals',
                'recipe_ar'         => '3-4 أكواب يوميًا بين الوجبات',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'obesity',
                'condition_name_fr' => 'Obésité',
                'condition_name_en' => 'Obesity',
                'condition_name_ar' => 'السمنة',
                'element_name_fr'   => 'Curcuma',
                'element_name_en'   => 'Turmeric',
                'element_name_ar'   => 'الكركم',
                'mechanism_fr'      => 'Métabolisme des graisses anti-inflammatoire',
                'mechanism_en'      => 'Anti-inflammatory fat metabolism',
                'mechanism_ar'      => 'استقلاب الدهون المضاد للالتهابات',
                'recipe_fr'         => '1 cuillère à café avec du poivre noir dans du lait tiède',
                'recipe_en'         => '1 tsp with black pepper in warm milk',
                'recipe_ar'         => 'ملعقة صغيرة مع الفلفل الأسود في حليب دافئ',
                'sort_order'        => 4,
            ],

            // ─────────────────────────────────────────────
            // 10. CHOLESTÉROL
            // ─────────────────────────────────────────────
            [
                'condition_key'     => 'cholesterol',
                'condition_name_fr' => 'Cholestérol',
                'condition_name_en' => 'Cholesterol',
                'condition_name_ar' => 'الكوليسترول',
                'element_name_fr'   => 'Nigelle',
                'element_name_en'   => 'Black Seed',
                'element_name_ar'   => 'حبة البركة',
                'mechanism_fr'      => 'Amélioration du profil lipidique',
                'mechanism_en'      => 'Lipid profile improvement',
                'mechanism_ar'      => 'تحسين مستوى الدهون في الدم',
                'recipe_fr'         => '1 cuillère à café d\'huile par jour',
                'recipe_en'         => '1 tsp oil daily',
                'recipe_ar'         => 'ملعقة صغيرة من الزيت يوميًا',
                'sort_order'        => 1,
            ],
            [
                'condition_key'     => 'cholesterol',
                'condition_name_fr' => 'Cholestérol',
                'condition_name_en' => 'Cholesterol',
                'condition_name_ar' => 'الكوليسترول',
                'element_name_fr'   => 'Ail',
                'element_name_en'   => 'Garlic',
                'element_name_ar'   => 'الثوم',
                'mechanism_fr'      => 'Réduction du LDL',
                'mechanism_en'      => 'LDL reduction',
                'mechanism_ar'      => 'تقليل الكوليسترول الضار',
                'recipe_fr'         => '2 gousses crues par jour',
                'recipe_en'         => '2 raw cloves daily',
                'recipe_ar'         => 'فصان نيئان يوميًا',
                'sort_order'        => 2,
            ],
            [
                'condition_key'     => 'cholesterol',
                'condition_name_fr' => 'Cholestérol',
                'condition_name_en' => 'Cholesterol',
                'condition_name_ar' => 'الكوليسترول',
                'element_name_fr'   => 'Avoine',
                'element_name_en'   => 'Oats',
                'element_name_ar'   => 'الشوفان',
                'mechanism_fr'      => 'Fibre de bêta-glucane',
                'mechanism_en'      => 'Beta-glucan fiber',
                'mechanism_ar'      => 'ألياف بيتا جلوكان',
                'recipe_fr'         => 'Un bol de flocons d\'avoine par jour',
                'recipe_en'         => 'Bowl of oatmeal daily',
                'recipe_ar'         => 'وعاء من الشوفان يوميًا',
                'sort_order'        => 3,
            ],
            [
                'condition_key'     => 'cholesterol',
                'condition_name_fr' => 'Cholestérol',
                'condition_name_en' => 'Cholesterol',
                'condition_name_ar' => 'الكوليسترول',
                'element_name_fr'   => 'Omega-3',
                'element_name_en'   => 'Omega-3',
                'element_name_ar'   => 'أوميغا 3',
                'mechanism_fr'      => 'Réduction des triglycérides',
                'mechanism_en'      => 'Triglyceride reduction',
                'mechanism_ar'      => 'تقليل الدهون الثلاثية',
                'recipe_fr'         => 'Complément d\'huile de poisson ou poisson gras 3 fois par semaine',
                'recipe_en'         => 'Fish oil supplement or fatty fish 3x/week',
                'recipe_ar'         => 'مكمل زيت السمك أو أسماك دهنية 3 مرات أسبوعيًا',
                'sort_order'        => 4,
            ],
        ];

        foreach ($remedies as $remedy) {
            PropheticRemedy::updateOrCreate(
                [
                    'condition_key'   => $remedy['condition_key'],
                    'element_name_fr' => $remedy['element_name_fr'],
                ],
                $remedy
            );
        }
    }
}
