<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\WorkoutSessionResource\Pages;
use App\Models\WorkoutSession;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Infolists;
use Filament\Infolists\Infolist;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class WorkoutSessionResource extends Resource
{
    protected static ?string $model = WorkoutSession::class;
    protected static ?string $navigationIcon = 'heroicon-o-calendar-days';
    protected static ?int $navigationSort = 4;

    public static function getNavigationGroup(): ?string
    {
        return __('filament.nav.user_management');
    }

    public static function getNavigationLabel(): string
    {
        return __('filament.resources.workout_sessions');
    }

    public static function getPluralModelLabel(): string
    {
        return __('filament.resources.workout_sessions');
    }

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count();
    }

    public static function getNavigationBadgeColor(): ?string
    {
        return 'purple';
    }

    public static function getGloballySearchableAttributes(): array
    {
        return ['user.name', 'theme', 'day'];
    }

    // Read-only resource - sessions are generated by the API
    public static function canCreate(): bool { return false; }
    public static function canEdit(Model $record): bool { return false; }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('user.name')
                    ->label('User')
                    ->searchable()
                    ->sortable()
                    ->icon('heroicon-o-user'),
                Tables\Columns\TextColumn::make('day')
                    ->label('Day')
                    ->badge()
                    ->color(fn (string $state): string => match (strtolower($state)) {
                        'monday', 'lundi' => 'info',
                        'tuesday', 'mardi' => 'success',
                        'wednesday', 'mercredi' => 'warning',
                        'thursday', 'jeudi' => 'danger',
                        'friday', 'vendredi' => 'purple',
                        'saturday', 'samedi' => 'gray',
                        'sunday', 'dimanche' => 'pink',
                        default => 'gray',
                    })
                    ->sortable(),
                Tables\Columns\TextColumn::make('theme')
                    ->label('Theme')
                    ->searchable()
                    ->sortable()
                    ->badge()
                    ->color('info'),
                Tables\Columns\TextColumn::make('exercises_count')
                    ->label('Exercises')
                    ->counts('exercises')
                    ->badge()
                    ->color('success'),
                Tables\Columns\IconColumn::make('has_warmup')
                    ->label('Warmup')
                    ->getStateUsing(fn (WorkoutSession $record): bool => !empty($record->warmup))
                    ->boolean()
                    ->toggleable(),
                Tables\Columns\IconColumn::make('has_finisher')
                    ->label('Finisher')
                    ->getStateUsing(fn (WorkoutSession $record): bool => !empty($record->finisher))
                    ->boolean()
                    ->toggleable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Generated')
                    ->dateTime('M d, Y')
                    ->sortable()
                    ->since(),
            ])
            ->defaultSort('created_at', 'desc')
            ->filters([
                Tables\Filters\SelectFilter::make('user')
                    ->relationship('user', 'name')
                    ->searchable()
                    ->preload(),
                Tables\Filters\SelectFilter::make('day')
                    ->options([
                        'Monday' => 'Monday',
                        'Tuesday' => 'Tuesday',
                        'Wednesday' => 'Wednesday',
                        'Thursday' => 'Thursday',
                        'Friday' => 'Friday',
                        'Saturday' => 'Saturday',
                        'Sunday' => 'Sunday',
                    ]),
                Tables\Filters\Filter::make('this_week')
                    ->label('This Week')
                    ->query(fn (Builder $query): Builder => $query->where('created_at', '>=', now()->startOfWeek())),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateHeading('No workout sessions yet')
            ->emptyStateDescription('Workout sessions are generated when users request a plan via the mobile app.')
            ->emptyStateIcon('heroicon-o-calendar-days');
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                Infolists\Components\Section::make('Session Details')
                    ->icon('heroicon-o-calendar-days')
                    ->schema([
                        Infolists\Components\TextEntry::make('user.name')
                            ->label('User')
                            ->icon('heroicon-o-user'),
                        Infolists\Components\TextEntry::make('user.email')
                            ->label('Email'),
                        Infolists\Components\TextEntry::make('day')
                            ->badge()
                            ->color('info'),
                        Infolists\Components\TextEntry::make('theme')
                            ->badge()
                            ->color('purple'),
                        Infolists\Components\TextEntry::make('created_at')
                            ->label('Generated')
                            ->dateTime('F j, Y g:i A'),
                    ])
                    ->columns(5),

                Infolists\Components\Section::make('Warmup')
                    ->icon('heroicon-o-fire')
                    ->schema([
                        Infolists\Components\TextEntry::make('warmup')
                            ->label('')
                            ->placeholder('No warmup defined'),
                    ])
                    ->collapsible(),

                Infolists\Components\Section::make('Exercises')
                    ->icon('heroicon-o-play-circle')
                    ->schema([
                        Infolists\Components\RepeatableEntry::make('exercises')
                            ->schema([
                                Infolists\Components\TextEntry::make('name')
                                    ->weight('bold'),
                                Infolists\Components\TextEntry::make('sets')
                                    ->badge()
                                    ->color('success'),
                                Infolists\Components\TextEntry::make('reps')
                                    ->badge()
                                    ->color('info'),
                                Infolists\Components\TextEntry::make('recovery')
                                    ->badge()
                                    ->color('warning'),
                                Infolists\Components\TextEntry::make('video_url')
                                    ->label('Video')
                                    ->url(fn (?string $state): ?string => $state)
                                    ->openUrlInNewTab()
                                    ->icon('heroicon-o-play')
                                    ->placeholder('No video'),
                            ])
                            ->columns(5),
                    ]),

                Infolists\Components\Section::make('Finisher')
                    ->icon('heroicon-o-flag')
                    ->schema([
                        Infolists\Components\TextEntry::make('finisher')
                            ->label('')
                            ->placeholder('No finisher defined'),
                    ])
                    ->collapsible(),
            ]);
    }

    public static function getRelations(): array
    {
        return [];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListWorkoutSessions::route('/'),
            'view' => Pages\ViewWorkoutSession::route('/{record}'),
        ];
    }
}
